import Head from "next/head";

import { api } from "appt3/utils/api";
import type { RouterOutputs } from "appt3/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Image from "next/image";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  // console.log(user);

  if (!user) return null;

  return <div className="flex w-full gap-3">
    <Image
      width={43}
      height={43}
      src={user.imageUrl}
      alt='user profile'
      className="flex w-14 h-14 rounded-full"
    />
    <input placeholder="type some text" className="grow bg-transparent outline-none" />
  </div>

};

type PostWithAuthor = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithAuthor) => {

  const { post, author } = props;

  return (
    <div className="p-4 border-b border-slate-400 flex w-full gap-3" key={post.id}>
      <Image
        width={43}
        height={43}
        src={author.imageUrl}
        alt='user profile'
        className="flex w-14 h-14 rounded-full"
      />
      <div className="flex flex-col">
        <div className="flex gap-1 text-slate-300">
          <span>{`@${author.username} `}</span>
          <span className="font-thin" >{` ${dayjs(post.createdAt).fromNow()} `}</span>
        </div>
        <span>
          {post.content}
        </span>
      </div>

    </div>
  );
}

export default function Home() {

  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading</div>

  if (!data) return <div>Something went wrong</div>

  // console.log(data);


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className=" h-full w-full md:max-w-2xl border-x border-slate-400   " >
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && <SignInButton />}
            {user.isSignedIn && <CreatePostWizard />}
          </div>

          <div className="flex flex-col" >
            {
              [...data, ...data]?.map((posts) =>
              (
                <PostView key={posts.post.id} {...posts} />
              ))
            }
          </div>

        </div>

      </main>
    </>
  );
}
